import dayjs from 'dayjs/esm';

import { IPmEtablissement, NewPmEtablissement } from './pm-etablissement.model';

export const sampleWithRequiredData: IPmEtablissement = {
  id: 24935,
  idEtablissementRPG: 'inasmuch',
  codePartenaireDistributeur: 'gee excepting brochure',
  numeroSiretSiege: 'allegation um er',
  codeEtat: 'all hurtful',
  libelleEtat: 'shrilly gee amidst',
  codeCategoriePersonne: 'boring beneath cutlet',
  libelleCategoriePersonne: 'gee aw',
  codeType: 'meh',
  dateCreationJuridique: dayjs('2025-05-29'),
  dateEtat: dayjs('2025-05-29'),
  dateFermetureJuridique: dayjs('2025-05-29'),
  codeIDCC: 'absolve ha',
  codeTrancheEffectif: 'joyfully',
  libelleTrancheEffectif: 'seldom diligently',
  dateCessationActivite: dayjs('2025-05-29'),
  dateEffectifOfficiel: dayjs('2025-05-30'),
  effectifOfficiel: 'fussy',
  codeMotifCessationActivite: 'probate rout essential',
  siret: 'indeed draft assail',
  codeTypeEtablissement: 'lovable',
  libelleEnseigne: 'underneath',
  codeNIC: 'ack',
};

export const sampleWithPartialData: IPmEtablissement = {
  id: 5384,
  idEtablissementRPG: 'when',
  codePartenaireDistributeur: 'scuffle ah',
  numeroSiretSiege: 'quinoa pear',
  codeEtat: 'phooey ick commercial',
  libelleEtat: 'whoa apud arrogantly',
  codeCategoriePersonne: 'midst than carefree',
  libelleCategoriePersonne: 'anenst resort',
  codeType: 'throughout times',
  dateCreationJuridique: dayjs('2025-05-29'),
  dateEtat: dayjs('2025-05-29'),
  dateFermetureJuridique: dayjs('2025-05-29'),
  codeIDCC: 'lively off',
  codeTrancheEffectif: 'past raw yet',
  libelleTrancheEffectif: 'solicit lest',
  dateCessationActivite: dayjs('2025-05-29'),
  dateEffectifOfficiel: dayjs('2025-05-30'),
  effectifOfficiel: 'grumpy while',
  codeMotifCessationActivite: 'gah dock',
  siret: 'repeatedly brr forswear',
  codeTypeEtablissement: 'yahoo energetically',
  libelleEnseigne: 'badly',
  codeNIC: 'until meh distorted',
};

export const sampleWithFullData: IPmEtablissement = {
  id: 22674,
  idEtablissementRPG: 'if yippee',
  codePartenaireDistributeur: 'pry task instead',
  numeroSiretSiege: 'good-natured ironclad',
  codeEtat: 'offset ugh fooey',
  libelleEtat: 'crackle wrongly',
  codeCategoriePersonne: 'for',
  libelleCategoriePersonne: 'tight marksman failing',
  codeType: 'er dress onto',
  dateCreationJuridique: dayjs('2025-05-30'),
  dateEtat: dayjs('2025-05-30'),
  dateFermetureJuridique: dayjs('2025-05-30'),
  codeIDCC: 'convoke follower',
  codeTrancheEffectif: 'hence yum once',
  libelleTrancheEffectif: 'hmph decide',
  dateCessationActivite: dayjs('2025-05-29'),
  dateEffectifOfficiel: dayjs('2025-05-30'),
  effectifOfficiel: 'velocity',
  codeMotifCessationActivite: 'consign',
  siret: 'terribly',
  codeTypeEtablissement: 'lazily',
  libelleEnseigne: 'throughout blowgun',
  codeNIC: 'before whoa',
};

export const sampleWithNewData: NewPmEtablissement = {
  idEtablissementRPG: 'illiterate as',
  codePartenaireDistributeur: 'apropos',
  numeroSiretSiege: 'as',
  codeEtat: 'so yet',
  libelleEtat: 'beneath unexpectedly earnest',
  codeCategoriePersonne: 'handsome carpool kookily',
  libelleCategoriePersonne: 'augment calmly',
  codeType: 'sprinkles black-and-white',
  dateCreationJuridique: dayjs('2025-05-29'),
  dateEtat: dayjs('2025-05-29'),
  dateFermetureJuridique: dayjs('2025-05-30'),
  codeIDCC: 'excitedly',
  codeTrancheEffectif: 'eek that',
  libelleTrancheEffectif: 'deselect glisten',
  dateCessationActivite: dayjs('2025-05-30'),
  dateEffectifOfficiel: dayjs('2025-05-29'),
  effectifOfficiel: 'sugary whenever in-joke',
  codeMotifCessationActivite: 'likewise shocked',
  siret: 'sans ack characterization',
  codeTypeEtablissement: 'until polished rarely',
  libelleEnseigne: 'worth restructure corner',
  codeNIC: 'expatiate mantua nervously',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
